use_frameworks!

target "TestSwiftyDropbox_iOS" do
    platform :ios, '13.0'
    pod 'SwiftyDropbox', :path => '../'
end

target "TestSwiftyDropbox_macOS" do
    platform :osx, '10.15'
    pod 'SwiftyDropbox', :path => '../'
end
